### ISSUE TITLE
Question. Technical reason for using eval?

### ISSUE THREAD

**Issue by joebartels** [thenables/thenify#11]
Hi, I'm curious on the reasoning behind using eval to promisify a function. I can see it's partially being used to construct named function and also conditionally add this bit, https://github.com/thenables/thenify/blob/master/index.js#L53
but is there more to it? 
Thanks :)

**Comment by jonathanong** [comment]
Just the named function as far as I recall

**Comment by joebartels** [comment]
Neat. thanks for sharing.
