### ISSUE TITLE
Fails when ran with 'use_strict'

### ISSUE THREAD

**Issue by bishtawi** [thenables/thenify#21]
I run node with the `--use_strict` option. This plugin fails with the message:

> SyntaxError: Unexpected eval or arguments in strict mode
>     at thenify (/Users/dev/work/node_modules/thenify/index.js:17:15)

**Comment by duckbrain** [comment]
This prevents it and packages that depend on it from being used in certain contexts, such as in the Atom editor. Why is eval needed?

**Comment by bishtawi** [comment]
I personally use [es6-promisify](https://github.com/digitaldesignlabs/es6-promisify) now. It doesnt use eval and is use_strict compatible. Ive even issued a PR to a package that I needed to use but couldnt due to the use_strict issue.
