### ISSUE TITLE
Arbitrary Code Execution Affecting thenify package, ALL versions

### ISSUE THREAD

**Issue by Rahul1408** [thenables/thenify#29]
Getting high severity vulnerability for thenify

Please check here: https://snyk.io/vuln/npm:thenify and provide the fixed version.

**Comment by dead-horse** [comment]
Thanks for the reminder, it was fixed in 3.3.1

**Comment by Rahul1408** [comment]
@dead-horse  high severity vulnerability is still there in 3.3.1

https://snyk.io/vuln/npm:thenify

**Comment by rajivshah3** [comment]
@Rahul1408 I think Snyk just needs to update their DB. I'll contact their support team as I'm getting this alert as well

**Comment by AdamGold** [comment]
Hey! Adam from Snyk here. I've updated our database and you should expect to see the changes within the next hours :)

**Comment by Rahul1408** [comment]
> Hey! Adam from Snyk here. I've updated our database and you should expect to see the changes within the next hours :)

thanks @AdamGold.  Just FYI, High severity vulnerability is still showing in 3.3.1. Will take more time in DB sync.

**Comment by Rahul1408** [comment]
> > Hey! Adam from Snyk here. I've updated our database and you should expect to see the changes within the next hours :)
> 
> thanks @AdamGold. Just FYI, High severity vulnerability is still showing in 3.3.1. Will take more time in DB sync.

it is fixed now with 3.3.1
